### ISSUE TITLE
Support for parameters via POST

### ISSUE THREAD

**Issue by AnalogJ** [jenkinsci/build-token-root-plugin#2]
Hi, I'm trying to use this plugin to with POSTed parameters and it doesn't seem to work.

If I append the parameters in the querystring everything works as expected but JSON or url-form-encoded bodies do not seem to be working.

This is unfortunate, as I was expecting the build-token-root plugin to have the same capabilities as the standard parameterized jobs

https://wiki.jenkins-ci.org/display/JENKINS/Remote+access+API

**Comment by jglick** [comment]
Please use JIRA for reporting issues.
